- src/ArduinoAVR/Repetier/Printer.cpp
- src/ArduinoDUE/Repetier/Printer.cpp
Hi,
I found some multiplies with zero witch I commented out. I am not really sure, but shouldn't you also use autolevelTransformation[1] to calculate the length of the first column vector? Shouldn't autolevelTransformation[1] also get divided by that length?
Kind regards,
Jan Phillip Willmann
PS: Your Software is GREAT WORK!!!
> Some changes on Printer::buildTransformationMatrix

- src/ArduinoDUE/Repetier/fastio.h
Hi Roland,
Alligator uses more pins than ArduinoDUE, I mapped these pin (PIN-92-100) in Fastio.h to resolve compile errors with Alligator board.
Thanks
> Additional fastio.h pins for Alligator board

- src/ArduinoAVR/Repetier/Commands.cpp
- src/ArduinoAVR/Repetier/Communication.cpp
- src/ArduinoAVR/Repetier/Communication.h
- src/ArduinoAVR/Repetier/Configuration.h
- src/ArduinoAVR/Repetier/HAL.h
- src/ArduinoAVR/Repetier/pins.h
Creates a new motherboard type (92) for the PrintrBoard Rev. F., which uses an MCP4728 DAC as a digital trimpot. 
Implements additional M-codes as PrintrBot's fork of Marlin does. (M907, M908, M909, and M910) - PrintrBot's fork of Marlin was used as a guide or reference implementation.
> Add MCP4728 DAC (Digital Trimpot) support for PrintrBoard Rev. F

- src/ArduinoAVR/Repetier/Printer.cpp
- src/ArduinoDUE/Repetier/Printer.cpp
Hi Roland,
In SAM processor during Powerup if the SD card is inserted cause a watchdog reset.
I solved by enabling watchdog before init sdcard.
> Watchdog enabled before sd init

- src/ArduinoAVR/Repetier/Configuration.h
- src/ArduinoAVR/Repetier/Printer.cpp
- src/ArduinoAVR/Repetier/Printer.h
- src/ArduinoDUE/Repetier/Configuration.h
- src/ArduinoDUE/Repetier/Printer.cpp
- src/ArduinoDUE/Repetier/Printer.h
When using a printer like the sparkcube it sometimes is better to connect three z axis steppers to three stepper drivers instead of two (two motors in parallel to z axis stepper driver, one motor to e1 stepper driver).
I've implemented this feature. You can enable it in configuration.h using the FEATURE_THREE_ZSTEPPER define.
> Implemented mirroring of Z axis to three stepper drivers

- src/ArduinoAVR/Repetier/Commands.cpp
- src/ArduinoAVR/Repetier/Printer.cpp
This patch adds JSON-formatted responses to M20 S2, M408 and M36.
This makes Repetier-Firmware work with ESP8266 Duet web interface, PanelDue and probably some other things.
Tested with RADDS and RAPMS 1.4.
> JSON-formatted responses (M408, M20 S2, M36)

- boards/Zonestar P802M/Configuration.h
- boards/Zonestar P802M/README.txt
Someone has changed Z-steps/mm from 400 to 1600, and at least one printer (apart from mine) had issue today. So I kept the change but added a comment about possible differences in printer hardware. Also fixed JSON part of config (using Web UI that is safer and cleaner).
Another fix is to disable watchdog in the config by default. Without it printer never boots if no SD card inserted (init time >1s).
> Zonestar config fixes

- src/ArduinoAVR/Repetier/ui.cpp
- src/ArduinoAVR/Repetier/ui.h
This patch frees up 3 or 4 wires of 6-wire 4-bit LCD connection by using
well-known shift register mod. That is important to implement extra features
on boards with not enough free GPIO pins such as Melzi.
**The code was tested** on modified Zonestar printer with Melzi board in both
2-wire and 3-wire versions. Both work well, but for 2-wire it was necessary
to use a real AND gate (74LS08) instead of diode/resistor due to long
wires between MCU/SR and LCD.
**The patch changes nothing of original code, it just adds one more type
of display.** An example of use is shown in ui.h for Zonestar controller.
It does not require any change of Web Configurator. Just 3 lines should
be added in user section to enable this version. Of course, they can also
be placed in uiconfig.h if necessary.
Many …
> Add support for displays connected using shift register (2/3-wire)

- src/ArduinoAVR/Repetier/HAL.cpp
This patch enables servo support on ATmega1284P boards.
Tested on Melzi (Zonestar P802M printer), used with mechanical Z-probe on a servo lever.
> HAL: enable servo option for ATmega1284P (Sanguino, Melzi, etc)

- src/ArduinoAVR/Repetier/HAL.cpp
Because stepperWait is only referenced by assembly code, the compiler
thinks that it can optimize it away.  We need to mark the variable as
used, so it sticks around.
> fix linker error for Arduino with LTO compilation

- boards/Zonestar P802M/Configuration_for_MEGA_and_RAMPS.h
There're many cases where Melzi board is failing, so it's very common to replace it with another option. This is the configuration for one of the most used options: MEGA & RAMPS.
The configuration is prepared for these options:
- RAMPS 1.4
- Arduino MEGA 2560 R3
- Drivers A4988
- LCD12864 3D Printer Controller Board Kit
> Configuration_for_MEGA_and_RAMPS.h

- src/ArduinoDUE/Repetier/HAL.h
Stop watchdog implementation in HAL.h is missing from Due side. This can cause a reset loop when hw setup takes a long time such as with 12864LCD.
> Fix Watchdog reset loop

- src/ArduinoAVR/Repetier/Extruder.cpp
- src/ArduinoDUE/Repetier/Extruder.cpp
as remaining issues with dual_x are related to re-selection of current extruder it's better to just skip executing the code. 
To not break any other setup that may still need (altough odd) the old behaviour it's just limited to DUAL_X_AXIS == 1
remade pull request as i forgot DUE files
> Fix DUAL X with LAZY_DUAL_X_AXIS disabled part 2

- src/ArduinoAVR/Repetier/Extruder.cpp
- src/ArduinoDUE/Repetier/Extruder.cpp
On a second thought, it is better for consistency to not skip the whole rest of the function for just 1 setup and not the rest
> Changed the fix for DUAL_X without LAZY_DUAL_X_AXIS.

- src/ArduinoAVR/Repetier/Commands.cpp
- src/ArduinoAVR/Repetier/Communication.cpp
- src/ArduinoAVR/Repetier/Communication.h
- src/ArduinoAVR/Repetier/Printer.cpp
- src/ArduinoAVR/Repetier/Printer.h
- src/ArduinoAVR/Repetier/Repetier.ino
- src/ArduinoAVR/Repetier/pins.h
- src/ArduinoDUE/Repetier/Commands.cpp
- src/ArduinoDUE/Repetier/Communication.cpp
- src/ArduinoDUE/Repetier/Communication.h
- src/ArduinoDUE/Repetier/Configuration.h
- src/ArduinoDUE/Repetier/Printer.cpp
- src/ArduinoDUE/Repetier/Printer.h
- src/ArduinoDUE/Repetier/Repetier.ino
- src/ArduinoDUE/Repetier/pins.h
This change introduces basic support for configuring TMC2130 drivers via SPI.
It has  so far only been tested on Arduino DUE + RADDS board + Watterott SilentStepSticks.
I'm waiting on additional stepper modules to arrive so I can test on Arduino Mega + RAMPS.
Sensorless homing IS possible (works for me) using this change, but works roughly.
Additional testing and tuning is required for smooth operation with sensorless homig.
I'm opening this PR to start the conversation around the implementation choices I've made so far.
Feedback and suggestions are highly appreciated.
Features (checked are completed):
@repetier Please have a look and let me know what you think so far. Thanks a lot!
>  Preliminary support for Trinamic TMC2130 drivers

- src/ArduinoAVR/Repetier/.gitignore
- src/ArduinoAVR/Repetier/Makefile
- src/ArduinoAVR/Repetier/get_arduino_libs.sh
This is an update to the last push that now supports both old and new avr-gcc compilers, and supports 1.0.5 through 1.8.4 versions of Arduino, and updates the sparse Arduino clone URL.
> Update makefile subsystem for ArduinoAVR stand alone make for all versions of Arduino

- src/ArduinoAVR/Repetier/Commands.cpp
- src/ArduinoAVR/Repetier/Communication.cpp
- src/ArduinoAVR/Repetier/Communication.h
- src/ArduinoDUE/Repetier/Commands.cpp
- src/ArduinoDUE/Repetier/Communication.cpp
- src/ArduinoDUE/Repetier/Communication.h
Like it is in Marlin firmware, I added a **M122** command to output TMC2130 diagnostic readings to read out many settings and additional runtime diagnostic output like if the motor is in stall or was shutdown due to over-temperature.
Example output from running M122 to the board:
```
Trinamic 2130 diagnostic readings:
X:	Y:	Z:	E0:	E1:
Enabled:	False	False	False	False	False
Set current:	500	500	500	500	500
RMS current:	489	489	489	489	489
Max current:	689	689	689	689	689
Run current:	16/32	16/32	16/32	16/32	16/32
Hold current:	8/32	8/32	8/32	8/32	8/32
CS actual:	8/32	8/32	8/32	8/32	8/32
PWM scale:	0	0	0	0	0
VSENSE:		0.180	0.180	0.180	0.180	0.180
Stealthchop:	True	True	True	True	True
Microsteps:	16	16	16	16	16
TSTEP:		1048575	1048575	1048575	1048575	1048575
PWM threshold:	0	0	0	0	0
OT …
```
> TMC2130 Diagnostic Reading with M122 command

- src/Repetier/src/drivers/stepper.cpp
- src/Repetier/src/drivers/stepper.h
- src/Repetier/src/io/io_stepper.h
I'm running the newest TMC2209 drivers that were recently released on my machine. I added some support for them with repetier V2 on a small forked repo of mine a little while ago. It's just a copy of the current TMC2208 classes/setup with some minor changes (individual UART addresses, stallgaurd4 etc).
- Stallguard4 uses values between 0-255. The stall sensitivity EEPROM/respective values were replaced with short instead of byte to support the new range (and the old range).
- I quickly added on a new flag (32) on line 132 for stepper.cpp just to display the correct value range to the user if they're using stallguard4 vs stallguard2. Could possibly be handled differently.
- I'm running these with the baudrate set to 500000, though they should support up to 700000 baud (stock fclk)
- …
> Support for TMC2209 drivers.

- src/Repetier/src/io/io_endstop_definitions.h
Small fix to bypass digitalPinToInterrupt checks for arm boards which may have pins defined beyond the 66 that function limits to.
> Allow ARM-based (due) boards to attach endstop hw switches to any pins.

- src/Repetier/src/communication/Commands.cpp
- src/Repetier/src/communication/gcode.cpp
Added M205 to the emergency parser as well to let repetier-server's interface read the eeprom even during long wait commands. 
In the original commit I mentioned that it only works around 7 times during waits. 
I believe I fixed this by adding M205 to the <PriorityCommands> tree on repetier-server's firmware xml file.
> Output EEPROM at any point using emergency parser.

- src/Repetier/src/Events.h
- src/Repetier/src/PrinterTypes/Printer.cpp
- src/Repetier/src/PrinterTypes/Printer.h
- src/Repetier/src/Repetier.h
- src/Repetier/src/communication/Commands.cpp
- src/Repetier/src/communication/Commands.h
- src/Repetier/src/communication/MCodes.cpp
- src/Repetier/src/controller/menu.cpp
- src/Repetier/src/main.cpp
Think this small fan delay/timeout functionality is useful to implement since more and more people are using enclosures that have fan/exhaust systems or more exotic configurations.
I chose the D parameter to avoid conflicting with any other firmware's gcode parameters (based off the [reprap g-code wiki](https://reprap.org/wiki/G-code#M106:_Fan_On))
Also added a EVENT_FAN_TIMEOUT(fanId, targetSpeed) event. Good for custom machines with custom actions (eg. motorized vents.)
Fan timeouts are checked with the 500ms timer inside Commands::checkForPeriodicalActions
I removed setFanSpeedDirectly as it seemed redundant and didn't see it in use anywhere else? I assumed it was a carry-over from V1. My apologies If you had plans for it.
<br/>
<i>(Updated)</i> Original Commit Desc: 
Adding a …
> Add M106 D<delay> parameter for fans.

- src/Repetier/src/boards/due/HAL.cpp
If our TIOB was overridden by an internal timer this small bit needs to be reapplied again to keep TIOB set as an output. 
Forgot about that small quirk on the SAM3X8E.
> Due Overridden TIOB TC_CMR_EEVT_XC0 Fix

- src/Repetier/src/drivers/heatManager.cpp
eeprom wasn't updating derived ki and kd values after being saved manually.
> EEPROM PID update derived ki/kd

- src/ArduinoAVR/Repetier/Commands.cpp
- src/ArduinoAVR/Repetier/DisplayList.h
- src/ArduinoAVR/Repetier/ui.cpp
- src/ArduinoAVR/Repetier/ui.h
Some slicers provides very good **time estimation and progress and exports it into GCODE** in the form of `M73` command.
This command provides progress in percentage as rgument `P` and remaining print time in minutes as argument `R`.
As there can be many types of displays, as most easy way seems to be to use message on display (same as command `M117`). Message with progress is displayed always when `M73` code is received and looks like in following example:
`[...74.   ] Rm 1:36`
Just note that `UIDisplay::setProgress` is here in the role of interface method, which may be modified in future to controll real progress bar on displays which supports that.
> Implements M73 prgress command

- src/Repetier/src/PrinterTypes/Printer.cpp
- src/Repetier/src/PrinterTypes/Printer.h
- src/Repetier/src/communication/MCodes.cpp
- src/Repetier/src/io/io_light.cpp
- src/Repetier/src/io/io_light.h
- src/Repetier/src/main.cpp
Small add-on for the io_lights module. PWM smoothed/fading light sources as well as M355 P<0..255> for general case light dimming.
Works with hardware and software PWM sources. 
The new macros are:
LIGHT_STATE_PWM(PWMCaseLightState)
LIGHT_SOURCE_PWM(caseLight, PWMCaseLight, PWMCaseLightState)
LIGHT_COND has a new 7th parameter for brightness (0-255) 
eg.
`LIGHT_COND(PWMCaseLightState, true, Printer::caseLightMode, 255, 255, 255, Printer::caseLightBrightness) `
The light fading takes place in the periodical actions timer and the default refresh rate is 30 milliseconds. Can be easily changed in io_light.h inside the LightStorePWM class. (beyond 50ms it becomes fairly choppy though.)
The duration of each fade transition is hard-coded at the moment in io_light.cpp, under the …
> add LIGHT_SOURCE_PWM

- src/Repetier/src/boards/due/HAL.cpp
this was slightly broken and was giving us the clock division rather than the clock divisor index. now works down to ~1.25hz on the due if necessary
> Due fix low frequency pwm

- src/Repetier/src/io/io_light.cpp
- src/Repetier/src/io/io_light.h
I missed this (and the previous statics, thanks)
Last winning condition now sets the mode and brightness properly on the next reset
> Fix PWM light condition execution conflict

- src/Repetier/src/io/io_temperature.h
Option for Steinhart-Hart/Beta generated thermistor readings. The C Coefficient is optional and can just be set 0 for a basic beta model instead. 
example:
IO_TEMPERATURE_BETA(TempExt2, IOAnalogExt2, 3950.0f, 5100.0f, 10000.0f, 0.0f)
IO_TEMPERATURE_BETA(name, analog, beta, seriesResistance, thermistorR25, cCoefficient)
> IO_TEMPERATURE_BETA

- src/Repetier/src/PrinterTypes/Printer.cpp
- src/Repetier/src/PrinterTypes/Printer.h
If PREVENT_Z_DISABLE_ON_STEPPER_TIMEOUT was set and the motors timed out, kill() would flood repetier server/host with temperature update prints until they crashed/froze
> Fix stepper timeout flood

- src/Repetier/src/boards/STM32F4/boards/rumba32.h
The HAL::analogEnable function maps the TEMP_x_PIN  to an analog channel using PinMap_ADC which uses PinNames enum from STM (PC_0) rather than the Arduino defines (PC0).
> Correct Rumba32 TEMP_x_PIN defines to match  PinMap_ADC

- src/Repetier/src/drivers/zprobe.cpp
I updated secureDistance to just be getBedDistance() * 1.5 in order to generate shorter maximum travel distances. There's also now a check for stepsRemaining to see whether or not the probe was ever triggered. This should mitigate some damage in case we have a bed crash, since it'll error out fairly quick.
I don't believe this secure distance value should have an issue with z max homing printers from what I can see? Though If anything, I can quickly change it. 
_Edit_: I noted in my original commit that I thought I found a small bug in stepsRemaining wherein rarely; a previous value would remain and then affect/append the next stepsRemaining value giving us erroneous results. 
After examining/debugging it again today, I can't seem to reproduce what I originally saw. My mistake.
> Z-Probe check if probe never triggered and fix secureDistance

- src/Repetier/src/drivers/zprobe.cpp
Sometimes (especially with a close bed distance, fast z feedrate) a probe could fail if we end up moving back to our optimum bed height before it finishes retracting. 
This adds a timeout/wait check if it's still active when we move back. 
If it's still active after 200ms then it's a failure.
(I've read my bltouch taking 20-30ms)
Allows us to set the bed distance slightly closer for faster probing speeds
> Z-Probe wait for probe if still activated

- src/Repetier/src/drivers/zprobe.cpp
- src/Repetier/src/drivers/zprobe.h
setXOffset/setYOffset were missing from default probe types
removed remnants of coating from the bltouch type
> Z-Probe mods compile fix

- src/Repetier/src/controller/drivers/Display20x4.cpp
Some menus with less than 4 menu items had ghosted text/rows from the previous menu (waitScreen did too)
I added a check to menuEnd to clear out any remaining rows if guiLine is less than our UI rows.
also added two row (1, 2) wipes to waitScreen which had a similar issue
> 20x4 Displays - Clear unused rows

- src/Repetier/src/controller/gui.cpp
Added a homing flag check before running a home command from the menus and added a check to prevent us from scrolling while the encoder is being held down.
> GUI Fix homing double clicks & scrolling clicks

- src/Repetier/src/Repetier.h
- src/Repetier/src/boards/STM32F4/HAL.cpp
- src/Repetier/src/boards/STM32F4/HAL.h
No servos but a beeper would cause a compile failure, watchdog, etc. 
Disabled SDSupport was still importing the CSVParser (which needs the sdfat library)
> STM32F4 Compile fixes

- src/Repetier/src/drivers/heatManager.cpp
- src/Repetier/src/drivers/heatManager.h
I think this menuSelectableP may have been in the wrong spot. Added a cursorRow adjustment after the menu is clicked to return the cursor upwards
I commented out the DynDeadTime control menu like the PID's just for now since it was overriding the base class's.
> GUI Hide disable button if heater isn't on

- src/Repetier/src/motion/MotionLevel1.cpp
Small bug-fix, we get a stepError here if autoleveling is on.
> Fix stepError after z raise

- src/Repetier/src/drivers/zprobe.cpp
Small find If the user's bltouch isn't wired up properly, or accidentally unplugged.
> ZProbe - Fix bltouch alarm loop

- src/Repetier/src/controller/drivers/Display20x4.cpp
- src/Repetier/src/controller/drivers/DisplayU8G2.cpp
- src/Repetier/src/controller/gui.cpp
- src/Repetier/src/controller/gui.h
Quickly wrote up these animations for selected rows with long titles on both display drivers
They're integrated in menuSelectable, menuSelectableP, menuText, and menuTextP right now
Mainly for long SDCard file names/vendor titles/info. Could be used later for long configuration option descriptions too etc.
> U8G2 & 20x4 Displays - added scrolling text for long selection strings 

- src/Repetier/src/controller/menu.cpp
- src/Repetier/src/controller/menu.h
- src/Repetier/src/drivers/zprobe.cpp
- src/Repetier/src/drivers/zprobe.h
I've added the control menu for ZProbes though at the moment it's quite small with only two options (Run Single Probe, Run Autoleveling) unless you're using the BLTouch. +(Deploy, Stow, Alarm Release, Self Test).
I first used Leveling::measure to run the Autoleveling command and runProbe for the Single Probe,
But I saw that there's routines for eg. ZMax printers that need to run after measuring at the GCode_ functions. 
In effort to run those correctly as well, I'm calling Commands::executeGCode with a GCode instance:
```
GCode innerCode;
innerCode.source = GCodeSource::activeSource;
innerCode.internalCommand = true;
innerCode.setG(32); // G32
Commands::executeGCode(&innerCode);
```
Are you alright with me accessing/manipulating the GCode class/functions like this? Or should I look for …
> ZProbe - Control menu 

- src/Repetier/src/io/io_light.h
Realized some of these high speed functions in IO_Beeper/IO_Lights i wrote a while back were never getting inlined/generating expensive vtable lookups. I don't think these three functions here needed to be virtual for now (IIRC)
> PWM Light sources remove unneeded virtual declarations 

- src/Repetier/src/Repetier.h
- src/Repetier/src/boards/SAMD51/HAL.cpp
- src/Repetier/src/boards/SAMD51/HAL.h
- src/Repetier/src/boards/STM32F4/HAL.cpp
- src/Repetier/src/boards/STM32F4/HAL.h
- src/Repetier/src/boards/due/HAL.cpp
- src/Repetier/src/boards/due/HAL.h
- src/Repetier/src/controller/drivers/Display20x4.cpp
- src/Repetier/src/controller/drivers/DisplayU8G2.cpp
- src/Repetier/src/controller/gui.cpp
- src/Repetier/src/controller/gui.h
I've split the init for both of these displays so that a new function (processInit()) is called during boot-up every GUI::update(). Should help displays that might require a slightly longer delay without slowing down boot.
I later extended this slightly to let us skip the intro screen if we attempt to scroll/click while it's animating.
Three gui boot states: 
```
GUIBootState::DISPLAY_INIT
GUIBootState::IN_INTRO
GUIBootState::READY
```
(Active/current state stored in GUI::curBootState)
The final thing was an addition to our HAL's to store our last boot reason; and displays a warning if we've had a watchdog reset or brownout. The reboot enums are: 
```
enum class BootReason {
SOFTWARE_RESET = 0,
BROWNOUT = 1,
LOW_POWER = 2,
WATCHDOG_RESET = 3,
EXTERNAL_PIN = 4,
POWER_UP = 5,
UNKNOWN = -1 …
```
> Async display init + skippable intro + show reboot warnings

- src/Repetier/src/communication/GCodes.cpp
- src/Repetier/src/motion/LevelingMethod.cpp
Added breakLongCommand checks during probe autoleveling so they're cancelable as well.
> Allow breakLongCommand during probes

- src/Repetier/src/PrinterTypes/Printer.cpp
- src/Repetier/src/PrinterTypes/Printer.h
- src/Repetier/src/communication/Communication.h
- src/Repetier/src/communication/Eeprom.cpp
- src/Repetier/src/communication/gcode.cpp
- src/Repetier/src/controller/menu.cpp
I added/implemented grabbing the USB host into the new GCodeSource class, and now we track a pointer to the usbHostSource if we have one. 
If we only have a native USB connection this hides the baud configuration option from the eeprom and menu since baud rate doesn't apply to native. (well, technically it still gets passed down from the host actually, but doesn't do anything with it)
It's purposely _only_ hidden in case the user adds another serial source (TFT, bluetooth etc) it shouldn't corrupt eeprom nor lose their settings.
Unfortunately the way i'm detecting the usb host is a naive-ish pointer compare with the "SerialUSB" class since there's no API available. The class seems pretty consistent across arduino platforms though, I don't think it should cause trouble. 
I did #if it out …
> Feature Hide baudrate config if only connected to nativeUSB

- src/Repetier/src/io/io_stepper.h
I was trying to figure out why my TMC2209's had connection issues/dropouts on my main due printer with HW-USART. 
Never noticed serial was creating interrupts at 60KHz-ish, and at priority 0.
( I could have sworn the serial classes defaulted to 15? ) 
I adjusted the TMC2209's to 115200 baud and set their priority to 5. (I also set the TMC08's priority to the same)
No more connection issues, and my steppers seem slightly quieter/smoother. 
Think this default baud/priority should be good for everyone?
> Fix HW TMC Stepper baud & IRQ priorities

- src/Repetier/src/controller/drivers/DisplayU8G2.cpp
The status bar text was riding on the edges of this U8G2 display and it looked a little odd/uncentered.
This adds a 1px of margin to it. Looks perfect now. 
Moved any text at X = 0px to X = 1px
Moved the top status text down just 1 px
(Line kept at the same height.)
Edit: Actually, is this too subjective or perhaps an issue with just my screen's very visible pixels? 
(I do really love the always-on status bar concept/setup, by the way.)
> GUI U8G2 - Offset all text 1px away from borders

- src/Repetier/src/u8g2/U8x8lib.cpp
- src/Repetier/src/u8g2/U8x8lib.h
_I split this separately from the HAL since it's a bit iffy._ 
Do you remember this? https://github.com/olikraus/u8g2/issues/749
For the STM32F1 I had to do the same workaround here.
I found the display needs a slower send speed while it's booting up to avoid a glitched first few rows, and it appears this display can't handle more than 700khz~ from what i last saw on my logic analyzer.
(I don't remember if the datasheet actually already mentioned that)
I did something experimental here which i'm unsure how it would be handled if i made a pull to u8g2 too. 
(eg is this too specific to *us* only?)
There needed to be a delay between bytes otherwise it'd glitch out since we'd be going too fast, but using nops would occasionally drag out the delay, especially while we're doing more complex …
> STM32F1 SW SPI U8G2 Displays

- src/Repetier/src/boards/STM32F1/boards/skr_mini_e3_v1_2.h
Added a ORIG_E0_MIN_PIN for the little E0-STOP header. (Filament runout)
Corrected ORIG_X_STEP_PIN. Was accidentally set to USART2 TX.
Coincidentally my x driver seems dead. Just gets endlessly hot even unplugged (internal short?).
I have a replacement board coming tomorrow though.
> SKR e3 mini - Wrong X-Step pin & Missing E0-STOP

- src/Repetier/src/PrinterTypes/Printer.cpp
- src/Repetier/src/communication/Commands.cpp
- src/Repetier/src/communication/Commands.h
- src/Repetier/src/communication/MCodes.cpp
compiling with LTO on the Due caused a weird compiler crash on this function. Looks like it's just because of the unused parameter.
(Did you still want a X show raw option?)
> printTemperatures remove unused showRaw parameter

- src/Repetier/src/motion/LevelingMethod.cpp
Hey, is this a typo and meant to be plane->z(curPosTransfX, curPosTransfY) ?
> Fix LevelingCorrector z plane correct wrong Y value (?)

- src/Repetier/src/Repetier.h
- src/Repetier/src/io/io_beeper.h
Found -O0 generated some linker vtable issues:
IO_Beeper base needed a virtual destructor
ServoInterface's functions just needed to be pure virtual
> Fix compiling under -O0

- src/Repetier/src/boards/due/HAL.h
- src/Repetier/src/communication/gcode.h
I had an issue where my SERIAL_BUFFER_SIZE on my due wasn't set to the default 128. This sometimes made emergency parser commands not work/get missed if the server was auto configured for the wrong size
This makes sure SERIAL_IN_BUFFER is set to SERIAL_BUFFER_SIZE if defined. Seems to fix the issue, though I'm slightly confused if it's meant to be its own independent size?
I also did this for SERIAL_RX_BUFFER_SIZE defined in the due's HAL in case it's used somewhere in the future.
> Fix emergency parser potentially wrong buffer size

- src/Repetier/src/communication/gcode.cpp
- src/Repetier/src/motion/MotionLevel1.cpp
If the tool had a start/end script -> executeFString creates a fake gcode object (without defining a source) ->
Commands::executeGCode updates the global activesource to this nullptr.  
We tried accessing that nullptr here in prefetch. 
I think we weren't meant to check the activesource here, but rather the source this is called in?
Edit: Actually taking another look at this, should the executeFString code source be set to flashSource as well? 
Sorry, I totally stalked that forum [post](https://forum.repetier.com/discussion/8084/dev2-tool-extruder-gcode-fail) and already had my debugger out. lol.  
Edit2: There was another specific possible toolscript crash I found with minAxisEndstops[Z_AXIS] if you had PRE_RAISE and a probe with a different class name (even with …
> executeFString gcode serial bug fix (multiple extruders)

- src/Repetier/src/boards/due/HAL.h
Looks like this flag needs to be enabled manually for the atmel-ice.
> Due - disable watchdog during debug breakpoints

- src/Repetier/src/boards/SAMD51/HAL.h
- src/Repetier/src/boards/STM32F1/HAL.h
- src/Repetier/src/boards/STM32F4/HAL.h
- src/Repetier/src/boards/due/HAL.h
- src/Repetier/src/controller/menu.cpp
I noticed changing the baudrate in the config menu didn't seem to actually change it when selected. 
I've changed it to update immediately once we exit the menu. 
To do this I've added serial end commands in each of the HAL's serialSetBaudrate to restart the serials at the new baudrate.
There's an included small check to avoid resetting the USB CDC connection. 
(I didn't add this check to the SAMD as I saw your previous commit where you excluded it from the gcodesource check)
It appears we also have a small bug where the baudrate currently gets reset to BAUDRATE on reboot. 
I *think* this is only happening with SDCard eeprom. I'll double check that when I get back.
> Baudrate config menu - update baudrate when exiting menu

- src/Repetier/src/boards/STM32F1/HAL.cpp
- src/Repetier/src/boards/STM32F4/HAL.cpp
Some low frequencies weren't getting played properly due to the lack of a prescaler.
> STM32F1/F4 - Fix tone timer prescaler

- src/Repetier/src/boards/STM32F4/HAL.cpp
Found out TIM11 doesn't have any channels other than 1 on the F4's, but we were trying to enable capture compare interrupts on channel 2, so they never triggered.
> STM32F4 Fix tone timer wrong channel

- src/Repetier/src/PrinterTypes/Printer.cpp
- src/Repetier/src/PrinterTypes/Printer.h
- src/Repetier/src/communication/Commands.cpp
- src/Repetier/src/communication/MCodes.cpp
- src/Repetier/src/main.cpp
Quickly added a P<milliseconds> parameter to let us change the rate we get auto temperature reports (for debugging etc). 
Minimum is 100ms, max is 10 seconds. 
Will always safely reset back to 1 second if P is omitted for best compatibility/host reconnects/errors etc.
> Add P<period ms> parameter to M155 autoreport

- src/Repetier/src/boards/STM32F1/boards/skr_mini_e3_v1_2.h
- src/SampleSystems/Cartesian/SKR E3 Mini V1.2/Configuration.h
- src/SampleSystems/Cartesian/SKR E3 Mini V1.2/Configuration_io_Mini_E3.h
Alright here's an example SampleSystem using the SKR E3 Mini v1.2 geared around the ender 3 with a bltouch. 
My problem is I don't actually own a bedslinger type printer and have never actually used one, just the classic gantry type. I assume this should work fine since they're not that different though.
The PID tune for the extruder's heater is correct, but the bed's PID tune is not. Trying to find someone with an ender and a good  PID tune for the stock bed. (Marlin uses bang bang for it) I'll update it as soon as I find a better tune.
I've removed a fair amount of older V1 deprecated macros from the main config that I saw were no longer in use.
I've also added a few tiny notes for the user in config.io about the light module, the stock display's buzzer and the heater hardware PWM. …
> SKR E3 Mini V1.2 SampleSystem Configuration 

- src/Repetier/src/boards/STM32F1/HAL.cpp
I previously set the ADC sample time/rate far too fast. Had a lot of jitter/bouncing at low temperatures. Guess the capacitors on those pins didn't have a chance to properly discharge. Temps much cleaner now.
> STM32F1 Adjust ADC sample rate

- src/ArduinoAVR/Repetier/Commands.cpp
- src/ArduinoDUE/Repetier/Commands.cpp
Per https://reprap.org/wiki/G-code#G92:_Set_Position
"A G92 without coordinates will reset all axes to zero on some
firmware."
My specific use case was so that I could easily repeat parts in Laser
mode, using generated G code that assumed absolute coordinates, knowing
the origin of each part.
> Make a bare G92 reset coordinates.

- src/Repetier/src/motion/MotionLevel1.cpp
Added a quick check to make sure we're moving the E axis before displaying the new cold extrusion warning.
Looks like we have a few places at the moment where we do something like oldCoordinates[E_AXIS] = currentPosition[E_AXIS] rather than IGNORE_COORDINATE before the moveByOfficial/Printer calls
Alternatively we could update those places to use IGNORE_COORDINATE i think.
(Wasn't sure if they may have been intentional and didn't want to break them.)
Edit: Actually, it looks like there's not really that many places that happens. Mostly in ZProbe.
Want me to just fix the responsible moveByX calls without IGNORE_COORDINATE on the E_AXIS and update this pull instead?
> Fix extra cold extrusion warnings on moves

- .gitattributes
Small OCD fix for the repo's languages bar statistic. Now shows the project/source as mostly C++/C.
Marked u8g2 as vendored so it's ignored. (It's a LOT of lines in C and overwhelms the stats)
Marked docs/html as documentation, ignored as well.
(Maybe you could also update the main V1 branch .gitattribute too)
> Update .gitattributes (Fix repo's language stats)

- src/Repetier/src/io/io_stepper.h
Ran into this too while setting up my HW TMC's. 
STM32Duino has setInterruptPriority for software serial and timers, but not HW serial. Didn't know that.
Maybe I shouldn't have added it here since it seems only the Due has that function?
> Fix STM32F1 compiling - missing setInterruptPriority

- src/Repetier/src/io/io_heatManager.h
time1 corrected to temp1, up1 corrected to timeUp1, etc.
> Fix HEAT_MANAGER_DYN_DEAD_TIME wrong parameter names

- src/Repetier/src/io/io_pwm.h
Small fix, was attempting kickstarting even at 80-100% speed.
> Only kickstart if new PWM is higher than current PWM

- src/Repetier/src/io/io_pwm.h
karl_ranseier suggested that it might be better to just kickstart only from zero pwm.
Figure since the fans are already moving with some sort of inertia, they don't really need any more kickstarting afterwards, even if they're spinning slowly. 
Seems to work okay with all my fans so far. 
IO_PWM_KICKSTART's parameter names needed a slight fix on some macros.
> PWM Kickstart - only from 0 & parameter names fix

- src/Repetier/src/motion/LevelingMethod.cpp
- src/Repetier/src/motion/MotionLevel1.cpp
CSV matrix importing caused a slight step error once finished importing.
The autolevel disable/enable print messages were very rarely causing some step errors during homing as well, I silenced them just for homing.
> Fix CSV Import step error & Fix homing step error

- src/Repetier/src/boardFiles/skr_mini_e3_v1_2/variant.h
- src/Repetier/src/boardFiles/skr_mini_e3_v2_0/variant.h
- src/Repetier/src/boards/STM32F1/HAL.cpp
- src/Repetier/src/boards/STM32F4/HAL.cpp
- src/Repetier/src/boards/due/HAL.cpp
- STM32's had their priority grouping set to 3 bits preempt, 1 bit sub priority. Adjusted them to 4 bits preempt, 0 sub since we're not using that feature & match Due. Shouldn't affect anything atm.
- E3 Mini's had their endstop interrupt priorities set to 6 by default. Adjusted to 1. 
- STM32F4 tone timer was missing it's setPriority, i'm not sure what it defaulted to. 
- I adjusted the Due's timer IRQ priorities to loosely match the other HAL's. They were quite low. I think I hear an extremely slight improvement in motion. (placebo?) 
- I set the STM32F1 set to the same priorities.
> STM32 & Due IRQ Priorities adjustment/fixes

- src/Repetier/src/drivers/endstops.h
- src/Repetier/src/drivers/zprobe.cpp
- src/Repetier/src/io/io_endstop_definitions.h
- src/Repetier/src/motion/MotionLevel1.cpp
- src/Repetier/src/motion/MotionLevel1.h
Smallish add-on to the endstop drivers. ( It should also work with merged endstops as well. ) and a function to Motion1 since it actually works well complimenting endstopForAxisDir. 
I've changed homing to attach the specific endstop we're going to use per axis. So far so good. 
ZProbe only attaches the ZProbe endstop at activate() and detaches at deactivate etc. 
Motion1::setHardwareEndstopsAttached(bool attach, EndstopDriver* specific = nullptr)
Attempts to detach/attach all axis HW endstops unless given a specific endstop driver to which to turn off.
Won't turn off any endstops if alwaysCheckEndstops is enabled. 
Hope I haven't missed anything with the other machine types though.
> Attachable/Detachable HW-Endstop interrupts when needed.

- src/Repetier/src/u8g2/U8x8lib.cpp
- src/Repetier/src/u8g2/u8x8_d_st7920.c
Figured out why I couldn't get the little simulation mode to render. TFT appears to only accept an active low clock signal.
Changed the SPI mode only for STM32F1's inside u8g2's st7920 display info.
> Fix SKR Mini - BTT TFT Simulation mode display

- src/Repetier/src/communication/MCodes.cpp
- src/Repetier/src/sdcard/SDCard.cpp
The BTT TFT Firmware was getting stuck waiting for a marlin response of "SD card ok" after attempting a M21 mount. 
I changed our previous print "Card successfully initialized." to it so the host doesn't lock up anymore. 
I added the SDCARD Cap if we have SDSUPPORT enabled. (Need to show the onboard SD menu option)
I also moved the SD card mounted UI_STATUS_UPD a bit in SDCard.cpp. It was still showing up as inserted even if we failed to read the sd.
> Add SDCARD cap & fix BTT TFT -> onboard sdcard menu freeze.

- src/Repetier/src/PrinterTypes/Printer.cpp
- src/Repetier/src/PrinterTypes/Printer.h
- src/Repetier/src/Repetier.h
- src/Repetier/src/communication/Commands.cpp
- src/Repetier/src/communication/Communication.cpp
- src/Repetier/src/communication/Communication.h
- src/Repetier/src/communication/MCodes.cpp
- src/Repetier/src/main.cpp
- src/Repetier/src/sdcard/SDCard.cpp
Just a quick clone of autoreport temperatures. Only autoreports byte positions during a SD print. Requires SDSUPPORT. 
I've brought in the S<seconds> parameter to M27 and M155 as well for better compatibility across hosts. 
Setting either P or S to 0 will disable autoreporting. Using both will just combine them.
Omitting P _and_ S for M27 will just print out the status as normal. Adding a C parameter will also print out the filename.
> Add AUTOREPORT_SD_STATUS cap & M27 C0 S<sec>P<millis> SD status Autoreports

- src/Repetier/src/boards/due/HAL.cpp
- src/Repetier/src/boards/due/HAL.h
We still have the Due's Real Time Timer available, and it looks like it can run just fast enough to replace the motion 2 timer.
Should free up some more precious PWM pins for us.
There were some weird caveats with it (forced 40us wait between restarts, can preempt itself), but I did some workarounds. 
Runs just the same as the timer now. 
In the HAL I've left it as an optional disable/enable feature in case it ever does create any problems for anyone.
(Alternatively it could replace the servo timer, etc)
> Due - Manipulate Real Time Timer to replace/free Motion2 timer

- src/Repetier/src/communication/Communication.h
Small additional printF function to print out any integer (8bit - 64bit) in binary. Optional grouping. 
Helped me out in the past when looking at HW/HAL status registers & datasheets. (debugger isn't always around, etc.) 
Might be useful for others doing similar as well.
Com::printBinaryFLN(PSTR(text), Template int, bool grouping)
> PrintBinaryFLN for debugging/register lookups.

- src/Repetier/src/communication/gcode.cpp
Fixes a really old problem with the native ports on Arduino Due's and the Arduino Library. 
Disconnecting the native port and then trying to serial write will cause an infinite loop. 
This works around the issue by checking if the USB port is in a suspend state before trying to write bytes.
Learned about using the suspend state from STM32. Used to check if they're connected or not in their HAL. 
(I think OS's have the choice to implement/broadcast suspend functionality or not, but so far it reliably changes state from my Pi and Windows desktop)
> Due - Fix Freeze/Hang on USB disconnects.

- src/Repetier/src/drivers/heatManager.cpp
Found the button wasn't properly reducing the row count/updating the extruder menu on 20x4's without back buttons.
> Fix extruder temp disable button

- src/Repetier/src/communication/Commands.cpp
- src/Repetier/src/communication/Commands.h
- src/Repetier/src/communication/GCodes.cpp
- src/Repetier/src/communication/MCodes.cpp
- src/Repetier/src/controller/menu.cpp
- src/Repetier/src/controller/menu.h
- src/Repetier/src/main.cpp
Added M575 to change baudrates. Matches the other firmwares and our menu option. M575 B<baudrate>
Only 38400, 56000, 57600, 76800, 115200, 128000, 230400, 250000, 256000, 460800, 500000 are accepted.
Can't change per serial yet.
> Implements M575 - Change Serial baudrate

- src/Repetier/platformio.ini
I saw STM32's use 14' by default but the SAM's and AVR don't. 
This should make them equal and gives us a few nifty things like constexpr functions with if's/variables, auto return types etc.
> Move SAM/AVR to C++14

- src/Repetier/src/drivers/endstops.cpp
- src/Repetier/src/drivers/endstops.h
- src/Repetier/src/io/io_endstop_definitions.h
- src/Repetier/src/utilities/constants.h
Small update to HW endstop switches, now uses a lambda as a callback passed through the constructor. Slims the structure a bit. Removed IO_TARGET_INIT as it's no longer required. 
I created a new global typedef; void_fn_t, in constants.h. Easier use of simple functors in the future.
> HW IO_Endstop - Lambda callbacks

- src/Repetier/src/motion/LevelingMethod.cpp
- src/Repetier/src/motion/MotionLevel1.cpp
Only the microstep string units are left for V2, I think. [microsteps] ? [µsteps] ? [-] ?
> Misc EEPROM text unit fixes

- src/Repetier/src/Repetier.h
- src/Repetier/src/communication/MCodes.cpp
- src/Repetier/src/controller/menu.cpp
- src/Repetier/src/sdcard/SDCard.cpp
Fixes manually unmounting the SDCard via M22. It would immediately remount itself. 
Menus now clear if they were still open, and the working directory now correctly resets.
> SDCard - Fix manual unmount remount & pop menus.

- src/Repetier/src/communication/Communication.cpp
- src/Repetier/src/communication/Communication.h
- src/Repetier/src/controller/drivers/Display20x4.cpp
- src/Repetier/src/controller/drivers/DisplayU8G2.cpp
- src/Repetier/src/controller/gui.cpp
- src/Repetier/src/controller/gui.h
- src/Repetier/src/motion/LevelingMethod.cpp
Adds a small animated leveling progress screen for both 20x4's and u8g2's. 
This is primarily for grid based leveling since it can take a fair bit of time.
But I believe it could be fit to work with the other leveling methods too.
(Sorry about the u8g2's probeProgress function being somewhat visually bloated, used a fair bit of constexpr margin variables to handle things.)
It looks like this:
> Feature - ZProbe Progress Screen

- src/Repetier/src/drivers/zprobe.cpp
- src/Repetier/src/drivers/zprobe.h
- src/Repetier/src/main.cpp
- src/Repetier/src/motion/LevelingMethod.cpp
- src/Repetier/src/motion/LevelingMethod.h
Hi. I've added these two parameters to let us change the repetitions and use-median setting for probe runs at runtime as well. Works across all leveling types. 
Z_PROBE_REPETITIONS and Z_PROBE_USE_MEDIAN are now the default settings if the parameters are omitted.
> ZProbe - G32 add R<repetitions> A<useMedian>

- src/Repetier/src/drivers/heatManager.cpp
- src/Repetier/src/io/io_tools.h
- src/Repetier/src/tools/tools.cpp
- Added Coarse/Fine menus for the extruder resolution menu to match the axis controls.
- The target temp increment feels far too slow on encoder speed 2, i've added a small check to increase it to 5 when on speed 2.
This is the only control so far that I felt needed this though, everything else seem fine.
- A few incorrect unit display fixes (MaxPWM, Extr. offsets, etc)
> Menus - Add Extr. Fine steps/mm menu & Misc Fixes

- src/Repetier/src/controller/menu.cpp
For mid-print changes.
Related: You think it'd be worthwhile to print the BabystepZ: messages in the periodical timer, and only after an amount of time (3ms-5ms) & if changed? (only do this if changed from the controller)
STM32F1 takes 500-700us per message...
My due takes 80-100us~
Maybe unnecessary...
> Add Babystep Z control to Tune menu

- src/Repetier/src/controller/menu.cpp
Just noticed controlling the temps on these two were missing while printing. 
I think it may also be a good idea to remove the home/move options from the tune menu? 
Or hide them unless paused, maybe.
> Fix missing bed/chamber tune controls

- src/Repetier/src/controller/drivers/Display20x4.cpp
- src/Repetier/src/controller/drivers/DisplayU8G2.cpp
- src/Repetier/src/controller/gui.h
- src/Repetier/src/controller/menu.cpp
Forgot to upload this tiny gui addition to help with large folders. Only shows up for U8G2's.
A thin simplish scrollbar appears at the right of the screen while the rows change. 
It disappears quickly after we stop moving to avoid blocking any important text. 
Made for the SD menus, but coincidentally works for all/any menus as well. I only added them to the sd menu. 
GUI::showScrollbar(GUIAction& action) <- auto calculates the bar based on top row, current row, length etc. 
Just drop before a menuEnd and the bar should appear if there's enough items on the screen.
GUI::showScrollbar(GUIAction& action, float percent, uint16_t min, uint16_t max) <- allows manual control
> GUI - SD Menu scroll bar

- src/Repetier/src/drivers/stepper.cpp
- src/Repetier/src/drivers/stepper.h
Are we still using this module for jam detection? I remember it was in the default IO configuration. Looks like the samplesystems changed a bit from last I looked.
Stepper Observable has a small bug where it'd prevent the tmc eeprom from showing if we added it's class to the motor list instead of the driver itself. 
This adds the driver's missing eepromHandler call, and adds a parent pointer check in motorIndex to find the correct motor list index.
> Steppers - Fix STEPPER_OBSERVEABLE TMC driver eeprom

- src/Repetier/src/controller/drivers/Display20x4.cpp
- src/Repetier/src/controller/drivers/DisplayU8G2.cpp
- src/Repetier/src/sdcard/SDCard.cpp
I added the ability for us to pass a newline character to waitScreen and for it to split the text onto the next row. Works with PSTR too. 
SD file writing now displays a busy status that shows the current written bytes and the current write speed. 
I tried keeping it all fairly lightweight.
> GUI - waitScreen newline & Write file show speed/written

- src/Repetier/src/Configuration.h
- src/Repetier/src/Repetier.h
- src/Repetier/src/motion/LevelingMethod.cpp
During long probes our beds can lose a bit of temperature if we're pausing all heaters. 
I've added this small feature to halt the probing and reheat if we stray too far from the target bed temp. 
By default it'll do it if we differ by more than 5c. It'll show a status message when this occurs.
I've added an adjustable macro for it incase the user wants it off, or at different threshold.
Z_PROBE_PAUSE_BED_REHEAT_TEMP.
> ZProbe - Reheat bed between grid probes if paused

- src/Repetier/src/PrinterTypes/Printer.cpp
- src/Repetier/src/Repetier.h
- src/Repetier/src/communication/MCodes.cpp
- src/Repetier/src/controller/gui.cpp
- src/Repetier/src/sdcard/SDCard.cpp
Some more SD related fixes. 
- Fixed an erroneous write timeout when sometimes beginning to write files.
- Volume label would sometimes have it's last character trimmed.
- SD mounting now correctly retries 3 times when manually mounting too. Would sometimes fail at Printer::setup. 
- Mounting and importing the SD card now takes place before eeprom init, allowing eeprom.bin to be checksummed for corruption. Only the SDCard type eeprom was still being corrupted whenever we modify/add eeprom options.
Well, In this commit I haven't added any restoreEEPROMSettingsFromConfiguration when it happens, so the corrupted settings are actually still set and applied right now.
I see storeDataIntoEEPROM has an unused corrupted parameter, but I'm not sure if it was deprecated for something else recently? …
> SD Card - Bug fixes / Eeprom corruption fix

- src/Repetier/src/Configuration.h
- src/Repetier/src/controller/drivers/Display20x4.cpp
- src/Repetier/src/controller/drivers/DisplayU8G2.cpp
- src/Repetier/src/controller/gui.cpp
- src/Repetier/src/controller/gui.h
- src/Repetier/src/controller/menu.cpp
Setting ENCODER_MAX_REPEAT_STEPS to 0 should compile out the encoder configuration stuff.
> GUI - Allow Compiling-out encoder repeat features

- src/Repetier/platformio.ini
- src/SampleSystems/Cartesian/SKR E3 Mini V1.2/Configuration.h
- src/SampleSystems/Cartesian/SKR E3 Mini V2/Configuration.h
Turning on -flto for STM32F1 since the E3's flash is getting a *little* tight with all features turned on.
PS. It turns out AVR has flto turned on by default now in PIO. 
Turning it off via unflag can speed up compile time a fair bit (if you have the RAM/flash to spare.)
> STM32F1 (Mini E3) - Add flto flag & enable dedicated SPI 

- src/Repetier/src/PrinterTypes/PrinterTypeCartesian.cpp
- src/Repetier/src/communication/Eeprom.cpp
- src/Repetier/src/communication/gcode.cpp
- src/Repetier/src/controller/drivers/DisplayU8G2.cpp
- src/Repetier/src/controller/gui.cpp
- src/Repetier/src/controller/menu.cpp
- src/Repetier/src/drivers/coolerManager.h
- src/Repetier/src/drivers/heatManager.cpp
- src/Repetier/src/drivers/heatManager.h
- src/Repetier/src/io/io_heatManager.h
few small fixes (some I forgot to merge a while back ago.)
- Fixed a rounding issue in the fan menu (PWM to %)
- Fixed potential nullptr dereference in the U8G display status line 
- Fixed potential out of bounds crash in eeprom.cpp handleprefix
- Fixed heatManagers not restoring their compiled maximum temperatures on eeprom resets
- Fixed maxInactivetime/stepperInactiveTime and baudrate not restoring on eeprom corruptions/resets
- Removed duplicate screen push & playDefaultSound in setStatus's warning level
- Removed some redundant checks in the hysteresis getters/setters in heatManager.h 
- Moved some assigned variables (inside class constructors) to their class initializer lists
- Forgot to remove the (ENCODER_SPEED == 2) ? 5 : 1 check inside the heater temperature menu
> V2 - Misc Fixes 

- src/Repetier/src/PrinterTypes/Printer.cpp
The pause/continue/stop menu options would disappear when printing via RepetierServer and we did a pause then continue.
Printer::setPrinting(true) was missing from Printer::continuePrint()
> Fix missing pause/stop options after RequestPause/RequestContinue

- src/ArduinoAVR/Repetier/gcode.cpp
- src/ArduinoDUE/Repetier/gcode.cpp
M20 list long name but command using this  if have a space are not working:
so this PR fix it for M23 / M30 / M32
M118 like M117 can have also space in it so sync with M117 
I have updated AVR/ DUE code- I hope is ok  - long time I did not do PR here ^_^ - let me know if I need to change something
I did not tested dev2 branch - as It seems I do not have supported board I have AVR which seems not yet ported in Readme, and my Due is dead sorry
> Allow space in commands M23 / M30 /  M32 / M118
