src/ArduinoAVR/Repetier/Extruder.cpp, src/ArduinoDUE/Repetier/Extruder.cpp
When manually changing flowrate the speed multiplier was changed as well.
Should change the flow rate not the feed rate when adjusting for filament diameter.
this is also issue 386 - will do a pull request next time.
=> changeFlowrateMultiply instead of changeFeedrateMultiply

src/ArduinoDUE/Repetier/Commands.cpp
Hi Roland,
good idea to set the current with a percentage, I need a small change for Alligator to fix compiler error .
Thanks
=> Fix Alligator MOTOR_CURRENT

src/ArduinoAVR/Repetier/Printer.cpp
Safer homing algorithm that ensures homing switches respond as expected during homing.
By checking the endstops status after each step in the homing sequence we can catch any sticky or faulty endstops.
This ensures that we do not blindly assume we are homed just because the routine finishes.
Avoids head crashes and potential damage/fire...
To test it, simply hold any (X,Y or Z tower) endstop when it is not supposed to, or prevent an axis from triggering their endstop when they try.
=> Safer homing algorithm for deltas

src/ArduinoAVR/Repetier/Printer.cpp
=> Fix command M408 (S2,S3,S4,S5)

src/ArduinoAVR/Repetier/pins.h
double definition de "THERMOCOUPLE_0_PIN"
=> MegaTronics 2.0 : double definition

src/ArduinoDUE/Repetier/Printer.cpp
=> Change debugLevel (toggleEcho)

src/ArduinoAVR/Repetier/Configuration.h, src/ArduinoDUE/Repetier/Configuration.h
=> Fix spelling errors in Configuration.h

src/ArduinoAVR/Repetier/Printer.cpp, src/ArduinoDUE/Repetier/Printer.cpp
I fixed misspelling in the error message shown while delta initialization fails.
=> fix typographical error

boards/Zonestar P802M/Configuration.h, boards/Zonestar P802M/README.txt
Just another new name for the same printer, it is sold from Aliexpress as 'Anet A8'.
=> Changed Zonestar P802M readme: added Anet A8-B name variant, updated configuration.h for Zonestar for 0.92.9 version

boards/Zonestar P802M/Configuration.h, boards/Zonestar P802M/README.txt, src/ArduinoAVR/Repetier/HAL.cpp, src/ArduinoAVR/Repetier/ui.cpp, src/ArduinoAVR/Repetier/ui.h
Nothing special here, just updated development branch with changes from master.
=> Just merged master branch into development

src/ArduinoDUE/Repetier/ui.cpp, src/ArduinoDUE/Repetier/uilang.h
… that were causing build errors.
These two changes seem to have been recently introduced via 'Improve dutch translations' commit.
They seem like small syntactic mistakes so I made the corrections in this PR.
@repetier
=> Fix some recent regressions 

src/ArduinoAVR/Repetier/Commands.cpp, src/ArduinoAVR/Repetier/Configuration.h, src/ArduinoAVR/Repetier/Eeprom.cpp, src/ArduinoAVR/Repetier/Extruder.cpp, src/ArduinoAVR/Repetier/Extruder.h, src/ArduinoAVR/Repetier/Printer.cpp, src/ArduinoAVR/Repetier/Printer.h, src/ArduinoAVR/Repetier/Repetier.ino, src/ArduinoDUE/Repetier/Commands.cpp, src/ArduinoDUE/Repetier/Configuration.h, src/ArduinoDUE/Repetier/Eeprom.cpp, src/ArduinoDUE/Repetier/Extruder.cpp, src/ArduinoDUE/Repetier/Extruder.h, src/ArduinoDUE/Repetier/Printer.cpp, src/ArduinoDUE/Repetier/Printer.h, src/ArduinoDUE/Repetier/Repetier.ino
Implement new dual x mode as discussed in https://forum.repetier.com/discussion/5837/dual-x-axis-improvements#latest
=> Implement new DUAL_X_AXIS_MODE

src/ArduinoDUE/Repetier/Configuration.h, src/ArduinoDUE/Repetier/DisplayList.h, src/ArduinoDUE/Repetier/pins.h
Add support for RURAMPS4D v1.3 board
=> Add support for RURAMPS4D v1.3 board

src/Repetier/src/boards/due/HAL.cpp
Set up timer PWMs for SAM3X8E. Allows all the possible timer pins to output PWM, including TIOA* TIOB*. 
Original Commit Desc:
Seamlessly integrated hardware based timer PWM mode for all the timer pins supported on SAM3X8E based boards. It's done alongside the normal hardware PWM io configuration. The only problem is you're currently still allowed to overlap/overwrite the original timers used for motion/beeper/servos, be warned as to which pins you use and which timers they belong to, to avoid this issue.
I have some code i'm currently working on which dynamically reassigns these stock timers to use any other available timers not used by the user, since we want the user's channels and configuration to have a bit of a higher priority.
=> Add support for Due Timer PWM's.

src/Repetier/src/boards/due/HAL.cpp
tc_local_chan wasn't being calculated correctly and didn't allow timers to be set on their proper respective channels. Somehow I didn't catch this issue before, or perhaps I fudged it during a diff in meld. Apologies. I've double checked as many timer pins as I could and all seem to be in working order again.
- Struct readability. 
- Clang formatted.
=> Due TimerPWMPin tc_local_chan fix

src/Repetier/src/drivers/coolerManager.cpp
max pwm limit was occasionally being bypassed. small typo i think
=> CoolerManager max pwm fix

src/Repetier/src/PrinterTypes/PrinterTypeCoreXYZ.cpp
Slight error causing mayhem...
=> Correct A motor copy-paste error

src/Repetier/src/io/io_pwm.h
Soft starting/soft stopping on pwm outputs. Helps reduce some of the violent surge/inrush current spikes when turning on high current loads (eg air cooling pumps, motors). 
Start delay/end delay are set independently. The threshold parameter that dictates how far away the target PWM must be from the current PWM in order to ramp up/down.
Ramping is done in the 100ms timer just like kickstart.
IO_PWM_RAMP(Pump1PWM, Pump1PWMHW, 5, 4, 45)
// 500ms ramp-up, 400ms ramp-down, threshold of 45.
It can be used on heater outputs too, but you may need to recalibrate your PID/dead-time settings.
=> IO_PWM_RAMP add-on

src/Repetier/src/controller/drivers/Display20x4.cpp
also blinks ???.? if z isn't homed.
=> 20X4 display bed/chamber temp cycle

src/Repetier/src/motion/LevelingMethod.cpp
=> fix CSV mesh export precision

src/Repetier/src/io/io_beeper.cpp, src/Repetier/src/io/io_beeper.h
https://github.com/repetier/Repetier-Firmware/pull/932#issuecomment-650559664
Conditions with the same theme shouldn't conflict anymore, nor should the last theme be repeated more than it should.
Conditions now correctly play all the way until playCount is reached. (By refilling the buffer when needed)
Conditions that were never "heard" but are still valid now play after leaving a higher ranked condition.
Sanity check for themes larger than the beep buffer
(Now needs a unique name)
TONE_THEME_COND(name, source, cond, theme, playTimes)
=> IO_Beeper condition conflict fix

src/Repetier/src/drivers/heatManager.cpp
printName addition to decoupled fast rising/holding reports
Small language fixes/changes
=> Heater name with decouple errors

src/Repetier/src/communication/Commands.cpp, src/Repetier/src/communication/MCodes.cpp
Just added serial flushes for emergency stop and watchdog
=> Serialflush before commanded resets

src/Repetier/src/drivers/heatManager.cpp
Updates targetTemperature while PID tuning (PID/Dyn)
This is mostly just to let repetier-server/host know the heater's on UI-wise
=> Autocalibrate set target temps

src/Repetier/src/boards/STM32F4/HAL.cpp
Just a pause and overflow change.
=> setHardwareFrequency for STM32F4's

src/Repetier/src/Configuration.h, src/Repetier/src/sdcard/SDCard.cpp
PS. What's the dummy init for?
=> define SD_SPI_SPEED_MHZ for config changes to SD SPI speeds

src/Repetier/src/communication/GCodes.cpp
Small message notification if called without any XYZ coordinates.
=> Add destination checking print

src/Repetier/src/io/io_pwm.h
Small casting issue that slipped by.
=> IO_PWM_RAMP compile fix

src/Repetier/src/Configuration.h, src/Repetier/src/Repetier.h, src/Repetier/src/drivers/zprobe.cpp, src/Repetier/src/drivers/zprobe.h
Added this as a setting for the eeprom and menus. Added a hint for the macro in config.h as well.
=> BLTouch configurable deploy/probe delay

src/Repetier/src/boards/STM32F1/fastSWSerial/SoftwareSerial.cpp
=> Fix STM32F1 SoftwareSerial wrong baud

src/Repetier/src/controller/gui.cpp
Added the warning sound setStatus played before
=> Boot warnings add missing warning sounds

src/Repetier/src/motion/LevelingMethod.cpp
Shortened the scoping syntax on this older autoimport code of mine.
No longer in widescreen :^)
=> Improve leveling autoimport code scoping/syntax

src/Repetier/src/communication/Commands.cpp, src/Repetier/src/communication/MCodes.cpp, src/Repetier/src/tools/extruder.h
M202 was using the wrong variable. Updated the command list comments.
Edit: Added isSecondaryMove() for the extruder tool. Will return true if it's an extrusion move OR a G1 move.
=> Fix M202 Max Accel/Travel Accel

src/Repetier/src/controller/gui.cpp, src/Repetier/src/controller/menu.cpp
Only rounded upon leaving a min/max limit or changing sign so that fine tuned increments stay incremented.
=> Menus - round to multiples of increments

src/Repetier/src/controller/drivers/Display20x4.cpp
Cycles between "Progress:" and print name every 4 seconds if not an SD print.
If it's an SD print it puts the name at the third row, where layer count would normally be.
=> Display cur. print layer and height for 20x4 displays

src/Repetier/src/boards/SAMD51/HAL.cpp, src/Repetier/src/boards/SAMD51/HAL.h, src/Repetier/src/boards/STM32F1/HAL.cpp, src/Repetier/src/boards/STM32F1/HAL.h, src/Repetier/src/boards/STM32F4/HAL.cpp, src/Repetier/src/boards/STM32F4/HAL.h, src/Repetier/src/boards/due/HAL.cpp, src/Repetier/src/boards/due/HAL.h, src/Repetier/src/communication/Commands.cpp
We'll definitely need this in the future for HAL specific tasks I feel. 
It's empty for all the HAL's right now though.
=> HAL - Add handlePeriodical

src/Repetier/src/controller/drivers/DisplayU8G2.cpp
Small fix, forgot to move this 1px too when we shifted everything to the right 1px.
=> U8G2's offset print progress box 1px right

src/Repetier/src/communication/MCodes.cpp
Fixes BTT TFT's onboard SD card detection if the sd card is already mounted.
=> SD - Fix M21 Host response 

src/Repetier/src/io/io_beeper.cpp, src/Repetier/src/io/io_beeper.h
I hadn't realized how much RAM the beeper class was taking up due to the beep buffer. 
Should help quite a fair bit (if a beeper is used anyways.)
=> IO_Beeper fixes & RAM reduction

src/Repetier/src/controller/drivers/DisplayU8G2.cpp
Was just using the wrong XBM function. 
(Finally got AVR to stop rebooting. My watchdog was still turning on after all.)
=> GUI - Fix bitmap display on AVR

src/Repetier/src/Configuration.h
Fix typos and grammar errors in comments.
=> Fix typos and grammar issues in Configuration.h

src/Repetier/src/motion/LevelingMethod.cpp
Fixes M323 S0 to turn off bump corrections.
=> Fix disabling bump distortion (M323 S0)
